name: test-node-CICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package
        run: |
          CURRENT_TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          VERSION_LABEL="${CURRENT_TIMESTAMP}_${GITHUB_SHA}"
          echo "::set-env name=VERSION_LABEL::$VERSION_LABEL"
          zip -r build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: 'AKIAZI2LE3BAUTXON4ZK'
          aws_secret_key: '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'
          application_name: 'test-node'
          environment_name: 'Test-node-env'
          version_label: ${{ env.VERSION_LABEL }}
          region: eu-north-1
          deployment_package: build.zip
